### ISSUE TITLE
Empty indicator on Bookmarks screen

### ISSUE THREAD

**Issue by lachlanwgordon** [weeklyxamarin/WeeklyXamarin.mobile#21]
If you go to the bookmaks screen before you've liked anything it looks broken. 

Maybe we should say something like "There's nothing here yet, swipe on an article to heart it and it will show up in your starred list".

**Comment by LuceCarter** [comment]
With ArticlesListPage being used for multiple different page types including Bookmark, how would we avoid displaying a message like this just because the editions haven't downloaded yet for example so the articles list is empty?
