### ISSUE TITLE
Apply infinite scroll to search page

### ISSUE THREAD

**Issue by gokujax** [weeklyxamarin/WeeklyXamarin.mobile#28]
I hope you apply infinite scroll to the search page instead of loading the whole result for better performance.

**Comment by lachlanwgordon** [comment]
Sounds like a good idea, there's definitely some perf to be gained by preventing adding items that aren't on screen. 

Be careful of the async enumerable which is returning items one at a time as soon as they're ready.

**Comment by kphillpotts** [comment]
Async Enumerable solves this problem
