### ISSUE TITLE
Create Model Objects

### ISSUE THREAD

**Issue by kphillpotts** [weeklyxamarin/WeeklyXamarin.mobile#4]
Create the model objects for the project. 

> Note: Given we are probably going to move away from Curated, we probably don't want to adhere too closely to what they are using, so we should just create a nice clean set of Model objects that suit our app.  

Issues
 * Issue Number
 * Issue Date
 * Issue Description
 * List Curators

Articles
 * Article ID
 * Title
 * Author (Reference to an author object?)
 * URL
 * Description
 * Issue Published
 * Category

Author
* Author ID
* Author Name
* Profile Photo URL
* Github URL
* WebPage URL
* Twitch URL
* YouTube URL
* Twitter URL
 
Event
* Event ID
* Title
* URL
* Date
* Event Type (Conference, User Group, Live Stream, Webinar)

**Comment by bricefriha** [comment]
Hi! I would be really happy to contribute to this project😃

About this issue specifically, I believe this would be relevant to clarify the type of every model's attributes. 
Even if this is obvious for most of them, that'd allow us to get a better overview, 
don't you think? ☺️
