### ISSUE TITLE
Be able to search / filter by Tags

### ISSUE THREAD

**Issue by kphillpotts** [weeklyxamarin/WeeklyXamarin.mobile#43]
Based on feedback from this review in the Play Store

https://play.google.com/console/u/0/developers/6368784618035709134/app/4976087531830244264/user-feedback/review-details?reviewId=gp%3AAOqpTOFPRhjQcxaXXoQFfhGHeFYG5tv95uxD1Sl8sfd_tG7233guOcf220jlr-7Lp1ltftXckapCuGMUyBUI1w&corpus=PUBLIC_REVIEWS

**Comment by lachlanwgordon** [comment]
Category search implemented in mobile and blazor
