### ISSUE TITLE
User can submit an article to weekly xamarin

### ISSUE THREAD

**Issue by kphillpotts** [weeklyxamarin/WeeklyXamarin.mobile#44]
Allow a user to submit an article to Weekly Xamarin

Probably via a share target.

As suggested in this review: https://play.google.com/console/u/0/developers/6368784618035709134/app/4976087531830244264/user-feedback/review-details?reviewId=gp%3AAOqpTOFPRhjQcxaXXoQFfhGHeFYG5tv95uxD1Sl8sfd_tG7233guOcf220jlr-7Lp1ltftXckapCuGMUyBUI1w&corpus=PUBLIC_REVIEWS

**Comment by lachlanwgordon** [comment]
Implented in Mobile app and Blazor, done with embeded google form
