### ISSUE TITLE
MVVM & DI Choices

### ISSUE THREAD

**Issue by adamhill** [weeklyxamarin/WeeklyXamarin.mobile#5]
Are there going to be any restrictions on using an MVVM framework vs INPC with a BaseViewModel? same question about DI container? I see this as a teaching opportunity to show how to do VM functional testing with Xamarin.Forms.Mocks.

What about *cool* infrastructure-y things like Fody, to cut down the property noise? (Assuming Simon will let us use it in a demo project. I am Patron in OC, if that makes a difference.)

**Comment by adamhill** [comment]
Sometimes the Universe provides ginormous hints - https://danielhindrikes.se/index.php/2020/04/21/introducing-tinymvvm-2-0/

**Comment by ybadragon** [comment]
I'm all for Fody :)

**Comment by kphillpotts** [comment]
I'm open to most MVVM frameworks and DI Frameworks. Personally I prefer to keep as "vanilla" as possible but if you reckon there is a need for a framework then I'm good with suggestions.  

Probably the only benefit I see of using a framework over just what's "in the box" is ViewModel based Navigation and perhaps constructor injection of services.

**Comment by lachlanwgordon** [comment]
My current interpretation of 'as "vanilla" as possible' is:
 - Shell Navigation
 - Microsoft.Extension.DependencyInjection
 - MVVM Helper(James Montemagno) for BaseViewModels, observables, ObservableRangeCollection, Async Commands.

Ok, I know that doesn't sound all that vanilla but... 
 - Shell navigation is in the box
 - MVVM Helpers has no dependencies but has a bunch of nifty helpers to make MVVM painless
 - Microsoft DI plays nicely with Xamarin and is the default for the webby parts of dotnet core so it the closest we have to a standard.

I find those bits play together really nicely together without enforcing too many framework opinions and they keep your code nice and portable.

Happy to help you get this setup on your stream or mine if we feel like heading this way.
