### ISSUE TITLE
Acknowledgements screen has text cut off at the top

### ISSUE THREAD

**Issue by kphillpotts** [weeklyxamarin/WeeklyXamarin.mobile#50]

**Comment by grimorde** [comment]
![image](https://user-images.githubusercontent.com/1989694/122217130-04c6df80-cea5-11eb-81ed-85471b18bdd6.png)

**Comment by grimorde** [comment]
*Update - I realised I se ethe issue more because I have my device set to large font (getting old!) but when I reset to normal I still see a text loss

Device: Pixel 5
![image](https://user-images.githubusercontent.com/1989694/122718113-6fd93300-d264-11eb-916c-6e16ec3c180f.png)

**Comment by kphillpotts** [comment]
Thanks, we have merged this - just changed it to an Auto to handle even longer lines
